security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        Symfony\Component\Security\Core\User\InMemoryUser: 'auto'

    providers:
        admin_fallback:
            memory:
                users:
                    hirehive29@gmail.com:
                        password: '$2b$10$sXODt5vz6QPXGmERgT/caulT5y2qVzQCirOTHzql1JyE8iSg9dToG'
                        roles: ['ROLE_ADMIN']
        app_user_provider:
            entity:
                class: App\Entity\Nour\User
                property: email
        chain_provider:
            chain:
                providers: ['admin_fallback', 'app_user_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: chain_provider
            form_login:
                login_path: app_login
                check_path: app_login
                success_handler: App\Security\LoginSuccessHandler
                username_parameter: _username
                password_parameter: _password
                enable_csrf: true
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/frontoffice, roles: ROLE_USER }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/backoffice, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
